# Generated by Django 2.0.1 on 2018-03-02 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pamsfeedback',
            name='fb_text',
            field=models.CharField(blank=True, max_length=200, verbose_name='fb_text'),
        ),
        migrations.AlterField(
            model_name='pamsfeedback',
            name='fb_type',
            field=models.CharField(blank=True, max_length=5, verbose_name='fb_type'),
        ),
    ]
