# Generated by Django 2.0.1 on 2018-03-02 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pams', '0002_auto_20180302_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pamsfeedback',
            name='fb_type',
            field=models.CharField(blank=True, max_length=10, verbose_name='fb_type'),
        ),
    ]
