# Generated by Django 2.0.1 on 2018-03-02 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pams', '0004_auto_20180302_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pamsanswer',
            name='team_1',
            field=models.CharField(blank=True, max_length=10, verbose_name='team_1'),
        ),
        migrations.AlterField(
            model_name='pamsanswer',
            name='team_2',
            field=models.CharField(blank=True, max_length=10, verbose_name='team_2'),
        ),
    ]
